language: node_js
sudo: true
node_js:
  - '7.1.0'
cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run dev
  - npm run build
  - npm run checkdir
after_script:
  - npm run coverage